export interface Speciality {
  id: string;
  slug: string;
  name: string;
  shortDesc: string;
  longDesc: string;
  iconName: string;
  emoji: string;
  keyTreatments: string[];
  conditionsTreated: string[];
  features: string[];
}

export const specialities: Speciality[] = [
  {
    id: 'general-medicine',
    slug: 'general-medicine',
    name: 'General Medicine',
    shortDesc: 'Diagnosis and treatment for a wide range of common and complex medical conditions.',
    longDesc: 'Our Department of General Medicine provides comprehensive diagnostic evaluations, chronic disease management, preventive health checks, and inpatient care for adult medical illnesses.',
    iconName: 'Stethoscope',
    emoji: '🩺',
    keyTreatments: [
      'Comprehensive Medical Consultations',
      'Diabetes & Hypertension Management',
      'Fever, Infection & Sepsis Protocol',
      'Preventive Health Screenings',
      'Geriatric & Adult Health Care',
    ],
    conditionsTreated: [
      'Type 1 & Type 2 Diabetes',
      'Hypertension & Metabolic Syndrome',
      'Acute Viral & Bacterial Infections',
      'Thyroid & Hormonal Imbalances',
      'Respiratory & Gastrointestinal Ailments',
    ],
    features: ['24/7 Inpatient Medical Care', 'Dedicated Consultation Suites', 'Integrated Diagnostic Protocols'],
  },
  {
    id: 'general-surgery',
    slug: 'general-surgery',
    name: 'General Surgery',
    shortDesc: 'Surgical evaluation and treatment with comprehensive pre- and post-operative care.',
    longDesc: 'Offering state-of-the-art open and minimally invasive laparoscopic surgical procedures led by expert surgical teams with modern sterile laminar flow operation theatres.',
    iconName: 'Scissors',
    emoji: '🔪',
    keyTreatments: [
      'Laparoscopic Appendectomy & Cholecystectomy',
      'Hernia Repair (Inguinal, Umbilical, Incisional)',
      'Trauma & Emergency Abdominal Surgery',
      'Minor Surgical & Daycare Procedures',
      'Pre- and Post-Operative Critical Care',
    ],
    conditionsTreated: [
      'Acute Appendicitis',
      'Gallbladder Stones & Disease',
      'Hernias & Hydrocele',
      'Surgical Infections & Abscesses',
      'Abdominal Trauma & Obstructions',
    ],
    features: ['Laminar Flow Modular OTs', 'Minimally Invasive Techniques', 'Rapid Post-Op Recovery Protocols'],
  },
  {
    id: 'cardiology',
    slug: 'cardiology',
    name: 'Cardiology',
    shortDesc: 'Medical evaluation and management of cardiovascular conditions.',
    longDesc: 'Dedicated cardiovascular evaluation and treatment unit focused on early detection, medical stabilization, and ongoing management of heart diseases and hypertension.',
    iconName: 'HeartPulse',
    emoji: '❤️',
    keyTreatments: [
      'Comprehensive Cardiac Evaluation',
      'ECG & 2D Echocardiography Support',
      'Hypertension & Coronary Disease Management',
      'Heart Failure Care Protocols',
      'Post-Cardiac Event Rehabilitation',
    ],
    conditionsTreated: [
      'Coronary Artery Disease',
      'Hypertensive Heart Disease',
      'Arrhythmias & Palpitations',
      'Congestive Heart Failure',
      'Lipid & Cholesterol Disorders',
    ],
    features: ['Immediate Emergency Triage', 'Continuous ECG Monitoring', 'Preventive Cardiology Counseling'],
  },
  {
    id: 'orthopaedics',
    slug: 'orthopaedics',
    name: 'Orthopaedics',
    shortDesc: 'Diagnosis and treatment for bone, joint, muscle and mobility-related conditions.',
    longDesc: 'Specialized orthopaedic care addressing bone fractures, joint pain, sports injuries, spine disorders, and comprehensive rehabilitation for enhanced patient mobility.',
    iconName: 'Bone',
    emoji: '🦴',
    keyTreatments: [
      'Complex Fracture Fixation & Trauma Care',
      'Joint Pain & Arthritis Management',
      'Spine & Back Pain Evaluation',
      'Casting, Splinting & Orthotic Support',
      'Post-Surgical Physiotherapy',
    ],
    conditionsTreated: [
      'Bone Fractures & Dislocations',
      'Osteoarthritis & Rheumatoid Arthritis',
      'Lumbar & Cervical Spondylosis',
      'Ligament & Tendon Injuries',
      'Osteoporosis & Bone Density Loss',
    ],
    features: ['Digital X-Ray on Site', '24/7 Emergency Trauma Care', 'Integrated Physiotherapy Unit'],
  },
  {
    id: 'paediatrics',
    slug: 'paediatrics',
    name: 'Paediatrics',
    shortDesc: 'Healthcare services focused on the medical needs of infants, children and adolescents.',
    longDesc: 'Compassionate pediatric healthcare ensuring gentle, patient-friendly medical consultations, developmental monitoring, immunization, and emergency pediatric management.',
    iconName: 'Baby',
    emoji: '👶',
    keyTreatments: [
      'Routine Child Health & Growth Checks',
      'Complete Immunization & Vaccination Schedules',
      'Pediatric Infection & Allergy Management',
      'Nutritional & Developmental Guidance',
      'Pediatric Emergency Care',
    ],
    conditionsTreated: [
      'Pediatric Fevers, Cough & Colds',
      'Childhood Asthma & Bronchitis',
      'Gastrointestinal Infections in Children',
      'Developmental Delays & Nutritional Deficiencies',
      'Neonatal & Infant Health Concerns',
    ],
    features: ['Child-Friendly Consultation Suites', 'Vaccination Tracking', 'Specialized Neonatal Protocols'],
  },
  {
    id: 'obstetrics-gynaecology',
    slug: 'obstetrics-gynaecology',
    name: 'Obstetrics & Gynaecology',
    shortDesc: 'Comprehensive women\'s healthcare, maternity and gynaecological services.',
    longDesc: 'Holistic care for women across all stages of life, from adolescent healthcare and prenatal maternity management to advanced gynecological surgical interventions.',
    iconName: 'UserCheck',
    emoji: '🤰',
    keyTreatments: [
      'Antenatal Care & Pregnancy Monitoring',
      'Normal & High-Risk Delivery Support',
      'Gynecological Evaluations & Screenings',
      'Menstrual Disorder Management',
      'Menopause & Hormonal Care',
    ],
    conditionsTreated: [
      'High-Risk Pregnancies',
      'PCOD / PCOS & Hormonal Imbalances',
      'Uterine Fibroids & Ovarian Cysts',
      'Pelvic Pain & Infections',
      'Infertility Initial Assessment',
    ],
    features: ['Private Labor & Delivery Suites', 'Ultrasound & Fetal Monitoring', 'Compassionate Female Staff Support'],
  },
  {
    id: 'neurosurgery',
    slug: 'neurosurgery',
    name: 'Neurosurgery',
    shortDesc: 'Specialised surgical care for conditions affecting the brain, spine and nervous system.',
    longDesc: 'Advanced neurological and neurosurgical department equipped to handle head injuries, spine compression, nerve disorders, and emergency neurotrauma stabilization.',
    iconName: 'Brain',
    emoji: '🧠',
    keyTreatments: [
      'Head Trauma & Concussion Management',
      'Spinal Disc & Nerve Decompression',
      'Stroke Emergency Stabilization',
      'Chronic Headache & Neuropathy Evaluation',
      'Neuro-Rehabilitation Planning',
    ],
    conditionsTreated: [
      'Head Injuries & Cranial Trauma',
      'Herniated Discs & Sciatica',
      'Seizure Disorders & Stroke',
      'Peripheral Neuropathy',
      'Cervical & Lumbar Spinal Stenosis',
    ],
    features: ['24/7 Neurotrauma ICU Support', 'Precision Imaging Diagnostics', 'Multidisciplinary Rehab Support'],
  },
  {
    id: 'pulmonology',
    slug: 'pulmonology',
    name: 'Pulmonology',
    shortDesc: 'Evaluation and treatment of respiratory and lung-related conditions.',
    longDesc: 'Dedicated pulmonary care covering asthma, bronchitis, COPD, pneumonia, and sleep-related breathing difficulties with respiratory therapy and pulmonary function evaluation.',
    iconName: 'Wind',
    emoji: '🫁',
    keyTreatments: [
      'Pulmonary Function Testing & Spirometry',
      'Nebulization & Oxygen Therapy Support',
      'Asthma & COPD Action Plans',
      'Post-COVID Respiratory Recovery',
      'Chest Infection Management',
    ],
    conditionsTreated: [
      'Bronchial Asthma & Allergies',
      'Chronic Obstructive Pulmonary Disease (COPD)',
      'Pneumonia & Chest Infections',
      'Sleep Apnea & Breathlessness',
      'Pleural Effusions & Chronic Cough',
    ],
    features: ['Advanced Nebulization Stations', 'Oxygen & BiPAP Support', 'Smoking Cessation Counseling'],
  },
  {
    id: 'ent',
    slug: 'ent',
    name: 'ENT (Ear, Nose & Throat)',
    shortDesc: 'Diagnosis and treatment of ear, nose and throat conditions.',
    longDesc: 'Complete diagnostic and therapeutic care for ear infections, hearing issues, sinusitis, tonsillitis, and speech or swallowing difficulties.',
    iconName: 'Headphones',
    emoji: '👂',
    keyTreatments: [
      'Diagnostic Endoscopy for ENT',
      'Sinusitis & Allergy Management',
      'Tonsillectomy & Adenoid Treatment',
      'Ear Discharge & Hearing Evaluation',
      'Foreign Body Removal',
    ],
    conditionsTreated: [
      'Chronic Sinusitis & Rhinitis',
      'Otitis Media & Hearing Impairment',
      'Tonsillitis & Pharyngitis',
      'Deviated Nasal Septum (DNS)',
      'Vertigo & Balance Disorders',
    ],
    features: ['High-Definition ENT Scopes', 'Daycare ENT Minor Procedures', 'Audiometric Diagnostics'],
  },
  {
    id: 'urology',
    slug: 'urology',
    name: 'Urology',
    shortDesc: 'Medical and surgical care for urinary tract and urological conditions.',
    longDesc: 'Expert urological consultations for kidney stones, prostate enlargement, urinary tract infections, and male reproductive health.',
    iconName: 'Activity',
    emoji: '🚻',
    keyTreatments: [
      'Kidney Stone Evaluation & Medical Management',
      'Prostate Enlargement (BPH) Treatment',
      'Recurrent UTI Management',
      'Endourological Procedures',
      'Urological Ultrasound & Diagnostics',
    ],
    conditionsTreated: [
      'Renal & Ureteric Calculi (Stones)',
      'Benign Prostatic Hyperplasia (BPH)',
      'Urinary Incontinence & Strictures',
      'Urinary Tract Infections (UTI)',
      'Male Health & Urological Conditions',
    ],
    features: ['Minimally Invasive Stone Removal Support', 'Comprehensive Uroflowmetry', 'Privacy Assured Consultations'],
  },
  {
    id: 'nephrology',
    slug: 'nephrology',
    name: 'Nephrology',
    shortDesc: 'Specialised care for kidney-related conditions and renal health.',
    longDesc: 'Comprehensive renal care department focused on early diagnosis, chronic kidney disease (CKD) staging, dialysis management, and renal protective strategies.',
    iconName: 'ShieldAlert',
    emoji: '🩸',
    keyTreatments: [
      'Renal Health Assessment & Screening',
      'Chronic Kidney Disease (CKD) Management',
      'Hemodialysis Support & Monitoring',
      'Glomerulonephritis Treatment',
      'Diabetic Nephropathy Care',
    ],
    conditionsTreated: [
      'Acute Kidney Injury & Renal Failure',
      'Chronic Kidney Disease (CKD)',
      'Proteinuria & Hematuria',
      'Electrolyte & Acid-Base Disorders',
      'Renal Hypertension',
    ],
    features: ['Dedicated Dialysis Unit Coordination', '24/7 Renal Lab Testing', 'Kidney Dietitian Support'],
  },
  {
    id: 'plastic-surgery',
    slug: 'plastic-surgery',
    name: 'Plastic Surgery',
    shortDesc: 'Reconstructive and specialised surgical procedures.',
    longDesc: 'Modern reconstructive surgery providing specialized care for burn injuries, trauma wound reconstruction, scar revision, and corrective soft tissue procedures.',
    iconName: 'Sparkles',
    emoji: '🧬',
    keyTreatments: [
      'Trauma Wound & Soft Tissue Reconstruction',
      'Burn Injury Management & Skin Grafting',
      'Scar Revision & Minimization',
      'Excision of Cysts & Skin Lesions',
      'Diabetic Foot Wound Care & Flaps',
    ],
    conditionsTreated: [
      'Post-Trauma Tissue Defects',
      'Burn Contractures & Scars',
      'Complex Non-Healing Wounds',
      'Benign Skin Lesions & Cysts',
      'Facial Trauma Lacerations',
    ],
    features: ['Aesthetic Suture Techniques', 'Sterile Minor OT Facility', 'Specialized Wound Healing Protocols'],
  },
  {
    id: 'surgical-gastroenterology',
    slug: 'surgical-gastroenterology',
    name: 'Surgical Gastroenterology',
    shortDesc: 'Specialised surgical management of gastrointestinal conditions.',
    longDesc: 'Dedicated surgical care for gastrointestinal disorders involving the stomach, intestines, liver, pancreas, and biliary system with advanced surgical techniques.',
    iconName: 'Crosshair',
    emoji: '🧑⚕️',
    keyTreatments: [
      'GI Tract Surgical Consultations',
      'Laparoscopic GI Procedures',
      'Biliary & Gallbladder Surgery',
      'Colorectal Disease Management',
      'Emergency GI Bleed & Perforation Care',
    ],
    conditionsTreated: [
      'Complex Gallbladder & Biliary Disease',
      'Intestinal Obstructions & Perforations',
      'Gastrointestinal Bleeding',
      'Pancreatic & Liver Conditions',
      'Hemorrhoids, Fissures & Fistula Care',
    ],
    features: ['Laparoscopic Towers', 'ICU Coordination for GI Emergencies', 'Dietary Recovery Guidance'],
  },
];

export function getSpecialityBySlug(slug: string): Speciality | undefined {
  return specialities.find((s) => s.slug === slug);
}
